name: On Demand Rebase
on:
  repository_dispatch:
    types: [rebase-command]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TWILL_PAT_TOKEN }}
          fetch-depth: 0
      - name: Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TWILL_PAT_TOKEN }}
